# Base Jekyll configuration

# Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Use _config.build.yml to override these settings on `grunt build`.

name: chromist
description:
url: http://chromist.org

authors:
  ragingwind:
    display_name: ragingwind
    email: ragingwind@gmail.com
    github: http://github.com/ragingwind
    twitter: http://twitter.com/ragingwind
    googleplus: https://plus.google.com/107574899030973045541/about

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: date

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Markdown library
markdown: kramdown

# Use Pygments to highlight code blocks
pygments: true
